import { StyleSheet } from 'react-native';
import { colors } from '../../utils/colors';
import { typography } from '../../utils/typography';
export const styles = StyleSheet.create({
  container: {
    flexGrow: 1,
    backgroundColor: '#f4f4f4ff',
    marginBottom: 65,
  },
  backButton: {
    width: 40,
    height: 40,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 10,
    shadowColor: '#979595ff',
    shadowOffset: { width: 0, height: 2 },
    borderRadius: 7,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 16,
    backgroundColor: '#fff',
  },
  empty: {
    width: 35,
    height: 35,
  },
  card: {
    backgroundColor: '#ffffff',
    borderRadius: 12,
    padding: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 5,
    overflow: 'hidden',
  },
  imageContainer: {
    backgroundColor: '#f5f5f5ff',
    borderRadius: 12,
    padding: 5,
    marginBottom: 8,
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
  },
  cardImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'contain',
  },
  cardTitle: {
    ...typography.h3,
    fontWeight: '700',
    textAlign: 'center',
    fontSize: 18,
    color: '#2D3748',
    marginBottom: 2,
  },
  cardSubtitle: {
    ...typography.body,
    textAlign: 'center',
    color: '#718096',
    marginBottom: 6,
  },
  enrollButton: {
    backgroundColor: '#ffdf20',
    paddingVertical: 10,
    borderRadius: 10,
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 3,
  },
  enrollButtonText: {
    ...typography.body,
    fontWeight: '700',
    textAlign: 'center',
    color: colors.primary,
  },
  searchContainer: {
    height: 50,
    margin: 12,
    borderRadius: 10,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#ffffffff',
    elevation: 10,
    shadowColor: '#d4d3d369',
  },
  searchText: {
    ...typography.heading,
    paddingHorizontal: 15,
  },
});
