import { StyleSheet } from 'react-native';
import { colors } from '../../utils/colors';
import { typography } from '../../utils/typography';

export const styles = StyleSheet.create({
  quizContainer: {
    flex: 1,
    backgroundColor: colors.primary,
  },
  quizHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 16,
    backgroundColor: colors.primary,
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  progressContainer: {
    flex: 1,
    marginRight: 16,
  },
  progressText: {
    ...typography.body,
    color: "gray",
    marginBottom: 8,
  },
  progressBar: {
    height: 6,
    backgroundColor: "#504184ff",
    borderRadius: 3,
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    backgroundColor: colors.yellow,
    borderRadius: 3,
  },
  timerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.primary,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  timerText: {
    ...typography.h3,
    color: colors.secondary,
    marginLeft: 6,
    fontWeight: '700',
  },
  scrollContent: {
    padding: 16,
    paddingBottom: 40,
  },
  questionContainer: {
    backgroundColor: colors.primary,
    paddingVertical: 25,
    paddingHorizontal: 5,
    borderRadius: 16,
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 1,
  },
  questionText: {
    ...typography.h3,
    fontSize: 22,
    fontWeight: '600',
    color: colors.secondary,
    marginVertical: 16,
    lineHeight: 28,
  },
  optionButton: {
    backgroundColor: colors.primary,
    padding: 16,
    borderRadius: 12,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: "#e3e2e2ff",
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  optionSelected: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  optionCorrect: {
    // backgroundColor: '#D1FAE5',
    borderColor: colors.success,
  },
  optionIncorrect: {
    // backgroundColor: '#FEE2E2',
    borderColor: colors.danger,
  },
  optionText: {
    ...typography.body,
    flex: 1,
    fontSize:20,
    color:colors.secondary
  },
  optionIcon: {
    marginLeft: 8,
  },
  nextButton: {
    backgroundColor: colors.yellow,
    padding: 16,
    borderRadius: 12,
    alignItems: 'center',
    marginTop: 16,
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
    flexDirection: 'row',
    justifyContent: 'center',
  },
  nextButtonText: {
    ...typography.h3,
    color: colors.primary,
    fontWeight: '600',
    marginRight: 8,
  },
});